CHANGELOG.md
Gemfile.lock
karafka-web.gemspec
lib/karafka/web.rb
lib/karafka/web/config.rb
lib/karafka/web/installer.rb
lib/karafka/web/ui/models/health.rb
lib/karafka/web/ui/pro/views/health/index.erb
lib/karafka/web/ui/views/shared/exceptions/not_found.erb

This PR makes the install process easier and tackles the complains related to getting 404 before first server run.

Install improvements

---

CHANGELOG.md
bin/karafka-web
karafka-web.gemspec
lib/karafka/web/ui/views/shared/exceptions/not_found.erb

Ppl have problems, I have solutions.

Add auto installer of the Web

---

CHANGELOG.md
Gemfile.lock
lib/karafka/web/processing/consumer.rb
lib/karafka/web/tracking/reporter.rb
lib/karafka/web/version.rb

close https://github.com/karafka/karafka/issues/1319

Target messages to proper partitions (#1319)

---

CHANGELOG.md
lib/karafka/web/installer.rb
lib/karafka/web/ui/app.rb
lib/karafka/web/ui/controllers/status.rb
lib/karafka/web/ui/models/status.rb
lib/karafka/web/ui/pro/app.rb
lib/karafka/web/ui/pro/controllers/status.rb
lib/karafka/web/ui/pro/views/shared/_navigation.erb
lib/karafka/web/ui/views/shared/_navigation.erb
lib/karafka/web/ui/views/shared/exceptions/not_found.erb
lib/karafka/web/ui/views/status/_breadcrumbs.erb
lib/karafka/web/ui/views/status/_failure.erb
lib/karafka/web/ui/views/status/_halted.erb
lib/karafka/web/ui/views/status/_success.erb
lib/karafka/web/ui/views/status/failures/_connection.erb
lib/karafka/web/ui/views/status/failures/_initial_state.erb
lib/karafka/web/ui/views/status/failures/_live_reporting.erb
lib/karafka/web/ui/views/status/failures/_partitions.erb
lib/karafka/web/ui/views/status/failures/_state_calculation.erb
lib/karafka/web/ui/views/status/failures/_topics.erb
lib/karafka/web/ui/views/status/show.erb

This PR introduces the /status page that allows for inspection of the Web UI setup state. It should help ppl having problems setting things up.
close https://github.com/karafka/karafka/issues/1318

Status page

---

lib/karafka/web/config.rb
lib/karafka/web/tracking/consumers/contracts/report.rb
lib/karafka/web/tracking/consumers/sampler.rb
lib/karafka/web/ui/models/process.rb
lib/karafka/web/ui/pro/views/consumers/_consumer.erb
lib/karafka/web/ui/pro/views/consumers/consumer/_metrics.erb
lib/karafka/web/ui/views/consumers/_consumer.erb
lib/karafka/web/ui/views/shared/_navigation.erb

close https://github.com/karafka/karafka/issues/1330

Allow for custom tags per consumer in the web ui

---

CHANGELOG.md
Gemfile.lock
lib/karafka/web/tracking/consumers/listeners/errors.rb
lib/karafka/web/tracking/reporter.rb
lib/karafka/web/version.rb

close https://github.com/karafka/karafka/issues/1344

Store consumer tags on errors

---

lib/karafka/web/ui/helpers/application_helper.rb
lib/karafka/web/ui/pro/views/consumers/_consumer.erb
lib/karafka/web/ui/pro/views/consumers/consumer/_metrics.erb
lib/karafka/web/ui/pro/views/errors/_detail.erb
lib/karafka/web/ui/pro/views/jobs/_job.erb
lib/karafka/web/ui/views/consumers/_consumer.erb
lib/karafka/web/ui/views/errors/_detail.erb
lib/karafka/web/ui/views/jobs/_job.erb

This PR ensures we use a common helper to render tags in all the places as the logic is the same.

Use helper to render tags

---

CHANGELOG.md
lib/karafka/web/tracking/consumers/listeners/errors.rb

This PR improves how error message is being extracted (inspired by Sidekiq).

Improve error message extraction

---

CHANGELOG.md
Gemfile.lock
lib/karafka/web/ui/controllers/cluster.rb
lib/karafka/web/ui/models/status.rb
lib/karafka/web/ui/views/cluster/_partition.erb
lib/karafka/web/ui/views/cluster/index.erb
lib/karafka/web/ui/views/shared/_pagination.erb
lib/karafka/web/ui/views/status/_warning.erb
lib/karafka/web/ui/views/status/show.erb
lib/karafka/web/ui/views/status/warnings/_pro_subscription.erb
lib/karafka/web/version.rb

close https://github.com/karafka/karafka-web/issues/31

Paginate cluster info and improve status

---

CHANGELOG.md
Gemfile.lock
lib/karafka/web/tracking/consumers/listeners/processing.rb
lib/karafka/web/version.rb
spec/lib/karafka/web/tracking/consumers/listeners/processing_spec.rb

close https://github.com/karafka/karafka/issues/1366

Fix not expected jid extraction on non-consumer errors

---

CHANGELOG.md
lib/karafka/web/ui/pro/views/errors/_detail.erb
lib/karafka/web/ui/views/errors/_detail.erb
lib/karafka/web/ui/views/routing/_detail.erb

close https://github.com/karafka/karafka-web/issues/46

Mask sasl credentials (#46)

---

CHANGELOG.md
Gemfile.lock
lib/karafka/web/ui/base.rb
lib/karafka/web/version.rb

close https://github.com/karafka/karafka-web/issues/55

Use CSP headers

---

lib/karafka/web/ui/controllers/base.rb
lib/karafka/web/ui/controllers/errors.rb
lib/karafka/web/ui/lib/paginations/offset_based.rb
lib/karafka/web/ui/lib/paginations/page_based.rb
lib/karafka/web/ui/pro/controllers/errors.rb
lib/karafka/web/ui/pro/controllers/explorer.rb
lib/karafka/web/ui/views/shared/_pagination.erb
spec/lib/karafka/web/ui/lib/paginations/offset_based_spec.rb
spec/lib/karafka/web/ui/lib/paginations/page_based_spec.rb

This PR improves the pagination by showing the range on offset-based pagination. It makes things more UX-friendly.

Improved offset range pagination labels

---

lib/karafka/web/cli.rb

This PR fixes a lack of replication factor in setup commands.

inject replicas count

---

lib/karafka/web/ui/pro/views/explorer/show.erb
spec/lib/karafka/web/ui/pro/controllers/explorer_spec.rb

close https://github.com/karafka/karafka-web/issues/95

Fix show of null message

---

CHANGELOG.md
lib/karafka/web/ui/base.rb
lib/karafka/web/ui/pro/app.rb
lib/karafka/web/ui/pro/controllers/explorer.rb
spec/lib/karafka/web/ui/pro/controllers/explorer_spec.rb

Part 1: https://github.com/karafka/karafka-web/issues/49
No JS, just backend and URL based API.

Support URL time based lookups for messages in explorer

---

CHANGELOG.md
lib/karafka/web/ui/pro/views/consumers/_consumer.erb
lib/karafka/web/ui/pro/views/explorer/show.erb
spec/lib/karafka/web/ui/pro/controllers/explorer_spec.rb

close https://github.com/karafka/karafka-web/issues/120

Fix displayed message size being to big and breaking UI on too many subscriptions

---

CHANGELOG.md

Release with the small UI patches.

v0.7.1 release

---

docker-compose.yml

ref https://github.com/karafka/karafka/issues/1636

rename docker kafka cluster id

---

lib/karafka/web/ui/app.rb
lib/karafka/web/ui/pro/app.rb

A small PR to align the routing styling with the rest of road routing

align roda routing styling

---

Gemfile.lock
karafka-web.gemspec

needed because of topic creation fixes.

depend on new karafka

---

CHANGELOG.md
lib/karafka/web/ui/helpers/application_helper.rb
lib/karafka/web/ui/pro/views/consumers/_counters.erb
lib/karafka/web/ui/views/consumers/_counters.erb

close https://github.com/karafka/karafka-web/issues/143
looks much better

format numbers in reporting counters

---

spec/lib/karafka/web/tracking/producers/reporter_spec.rb

close https://github.com/karafka/karafka-web/issues/171

Use real error when testing

---

CHANGELOG.md
Gemfile.lock
lib/karafka/web/ui/pro/views/routing/_detail.erb
lib/karafka/web/ui/views/routing/_detail.erb
lib/karafka/web/version.rb
spec/lib/karafka/web/ui/controllers/routing_spec.rb

close https://github.com/karafka/karafka-web/issues/173

Fix visible sasl/ssl

---

spec/lib/karafka/web/management/migrations/1700234522_introduce_waiting_in_consumers_metrics_spec.rb
spec/lib/karafka/web/management/migrations/1700234522_introduce_waiting_in_consumers_state_spec.rb
spec/lib/karafka/web/management/migrations/1700234522_remove_processing_from_consumers_metrics_spec.rb
spec/lib/karafka/web/management/migrations/1700234522_remove_processing_from_consumers_state_spec.rb

This PR adds missing migrations specs.

Add missing migrations specs

---

lib/karafka/web/ui/controllers/base.rb
lib/karafka/web/ui/controllers/cluster.rb
lib/karafka/web/ui/controllers/consumers.rb
lib/karafka/web/ui/controllers/jobs.rb
lib/karafka/web/ui/controllers/routing.rb
lib/karafka/web/ui/helpers/application_helper.rb
lib/karafka/web/ui/lib/sorter.rb
lib/karafka/web/ui/pro/controllers/cluster.rb
lib/karafka/web/ui/pro/controllers/consumers.rb
lib/karafka/web/ui/pro/controllers/health.rb
lib/karafka/web/ui/pro/controllers/jobs.rb
lib/karafka/web/ui/pro/controllers/routing.rb
lib/karafka/web/ui/pro/views/consumers/index.erb
lib/karafka/web/ui/pro/views/consumers/pending_jobs.erb
lib/karafka/web/ui/pro/views/consumers/running_jobs.erb
lib/karafka/web/ui/pro/views/jobs/pending.erb
lib/karafka/web/ui/pro/views/jobs/running.erb
lib/karafka/web/ui/pro/views/routing/_consumer_group.erb
lib/karafka/web/ui/views/consumers/index.erb
lib/karafka/web/ui/views/jobs/pending.erb
lib/karafka/web/ui/views/jobs/running.erb
lib/karafka/web/ui/views/routing/_consumer_group.erb
spec/lib/karafka/web/ui/lib/sorter_spec.rb

Small improvements to the sorting engine:
- limits the attributes to only allowed
- provides an option to reverse arrow when the attribute sort is reverse of naming convention
- adds some specs
- provides option to sort routing

Sort improvements

---

CHANGELOG.md
lib/karafka/web/ui/pro/views/consumers/_consumer.erb

This just reorganizes the pro consumers list to show topic assignments on a CG level..

Support multiplexing

---

CHANGELOG.md
Gemfile.lock
lib/karafka/web/config.rb
lib/karafka/web/tracking/consumers/listeners/booting.rb
lib/karafka/web/tracking/producers/listeners/booting.rb
lib/karafka/web/tracking/scheduler.rb
lib/karafka/web/version.rb
spec/lib/karafka/web/tracking/consumers/listeners/booting_spec.rb
spec/lib/karafka/web/tracking/producers/listeners/booting_spec.rb

close https://github.com/karafka/karafka-web/issues/269

Defer scheduler creation

---

CHANGELOG.md
lib/karafka/web.rb
lib/karafka/web/tracking/consumers/listeners/booting.rb
lib/karafka/web/tracking/consumers/sampler.rb
lib/karafka/web/ui/helpers/application_helper.rb
lib/karafka/web/ui/models/process.rb
lib/karafka/web/ui/pro/views/consumers/subscriptions.erb
lib/karafka/web/ui/pro/views/health/changes.erb
lib/karafka/web/ui/pro/views/health/lags.erb
lib/karafka/web/ui/pro/views/health/offsets.erb
lib/karafka/web/ui/pro/views/health/overview.erb
spec/lib/karafka/web/ui/models/process_spec.rb

close https://github.com/karafka/karafka-web/issues/276
close https://github.com/karafka/karafka-web/issues/275
close https://github.com/karafka/karafka-web/issues/274

Swarm support + minor fixed

---

CHANGELOG.md
Gemfile.lock
lib/karafka/web/config.rb
lib/karafka/web/contracts/config.rb
lib/karafka/web/ui/pro/controllers/dlq.rb
lib/karafka/web/version.rb
spec/lib/karafka/web/contracts/config_spec.rb
spec/lib/karafka/web/ui/pro/controllers/dlq_spec.rb

close https://github.com/karafka/karafka-web/issues/281

Auto-qualify topics with DLQ/dlq/dead_letter_queue postfixes to DLQ view

---

CHANGELOG.md
lib/karafka/web/ui/helpers/application_helper.rb
lib/karafka/web/ui/pro/views/consumers/_breadcrumbs.erb
lib/karafka/web/ui/pro/views/consumers/_consumer.erb
lib/karafka/web/ui/pro/views/consumers/index.erb
lib/karafka/web/ui/pro/views/dashboard/index.erb
lib/karafka/web/ui/pro/views/health/_partition.erb
lib/karafka/web/ui/pro/views/jobs/_job.erb
lib/karafka/web/ui/public/javascripts/charts.js
lib/karafka/web/ui/public/stylesheets/application.css
lib/karafka/web/ui/views/consumers/_consumer.erb
lib/karafka/web/ui/views/jobs/_job.erb
spec/lib/karafka/web/ui/helpers/application_helper_spec.rb

Few small UI improvements

---

CHANGELOG.md
lib/karafka/web/ui/pro/controllers/consumers.rb
lib/karafka/web/ui/pro/controllers/explorer.rb
lib/karafka/web/ui/pro/controllers/messages.rb
lib/karafka/web/ui/pro/controllers/routing.rb
lib/karafka/web/ui/pro/lib/patterns_detector.rb
spec/lib/karafka/web/ui/pro/controllers/explorer_spec.rb
spec/lib/karafka/web/ui/pro/controllers/messages_spec.rb
spec/spec_helper.rb

close https://github.com/karafka/karafka-web/issues/295

fix lack of pattern detection

---

CHANGELOG.md
lib/karafka/web/ui/lib/safe_runner.rb
lib/karafka/web/ui/pro/controllers/explorer.rb
lib/karafka/web/ui/pro/views/explorer/_failed_deserialization.erb
lib/karafka/web/ui/pro/views/explorer/_message.erb
lib/karafka/web/ui/pro/views/explorer/message/_metadata.erb
lib/karafka/web/ui/pro/views/explorer/message/_payload.erb
lib/karafka/web/ui/pro/views/explorer/message/_payload_actions.erb
lib/karafka/web/ui/pro/views/explorer/messages/_headers.erb
lib/karafka/web/ui/pro/views/explorer/messages/_key.erb
spec/lib/karafka/web/ui/controllers/routing_spec.rb
spec/lib/karafka/web/ui/lib/safe_runner_spec.rb
spec/lib/karafka/web/ui/pro/controllers/explorer_spec.rb
spec/lib/karafka/web/ui/pro/controllers/messages_spec.rb
spec/support/helpers/topics_manager_helper.rb

This PR supports headers and key deserialization with a failover and a message.

support failed headers, etc

---

CHANGELOG.md
lib/karafka/web/pro/ui/views/consumers/_consumer_controls.erb
lib/karafka/web/ui/public/javascripts/application.js
lib/karafka/web/ui/views/shared/_header.erb

close https://github.com/karafka/karafka-web/issues/313

support page titles

---

CHANGELOG.md
Gemfile.lock
lib/karafka/web/config.rb
lib/karafka/web/contracts/config.rb
lib/karafka/web/management/actions/enable.rb
lib/karafka/web/pro/commanding/config.rb
lib/karafka/web/pro/commanding/contracts/config.rb
lib/karafka/web/pro/commanding/listener.rb
lib/karafka/web/ui/models/status.rb
lib/karafka/web/version.rb
spec/lib/karafka/web/contracts/config_spec.rb
spec/lib/karafka/web/ui/models/status_spec.rb

close https://github.com/karafka/karafka-web/issues/243

Align `processing.consumer_group` to `admin.group_id`  for consistency

---

CHANGELOG.md
Gemfile.lock
lib/karafka/web/ui/views/consumers/_consumer.erb
lib/karafka/web/version.rb
spec/lib/karafka/web/ui/controllers/consumers_controller_spec.rb

close https://github.com/karafka/karafka-web/issues/328

fix missing stored lag reference in OSS consumers

---

CHANGELOG.md
Gemfile.lock
lib/karafka/web/errors.rb
lib/karafka/web/management/actions/enable.rb
lib/karafka/web/version.rb
spec/lib/karafka/web/management/actions/enable_spec.rb

close https://github.com/karafka/karafka-web/issues/333

prevent web from being configured before karafka

---

CHANGELOG.md
Gemfile
Gemfile.lock
lib/karafka/web/ui/controllers/base_controller.rb
spec/spec_helper.rb

close https://github.com/karafka/karafka-web/issues/343
I am NOT adding 3.4-preview1 yet because I want to roll it out to all components BUT I did run all specs locally to ensure consistency.

ruby 3.4 fixes

---

CHANGELOG.md
lib/karafka/web/ui/public/javascripts/application.js
lib/karafka/web/ui/public/javascripts/live_poll.js
lib/karafka/web/ui/views/shared/_live_poll.erb

Small improvements to live polling

live poll improvements

---

CHANGELOG.md
lib/karafka/web/ui/models/status.rb
lib/karafka/web/ui/views/status/failures/_materializing_lag.erb
lib/karafka/web/ui/views/status/show.erb
spec/lib/karafka/web/ui/controllers/status_controller_spec.rb
spec/lib/karafka/web/ui/models/status_spec.rb

close https://github.com/karafka/karafka-web/issues/362

validate states lag

---

CHANGELOG.md
lib/karafka/web/tracking/consumers/listeners/connections.rb
lib/karafka/web/tracking/consumers/sampler.rb

just small remarks since we don't need sub-ms precision.

round detailed values

---

CHANGELOG.md
lib/karafka/web/pro/commanding/commands/base.rb
lib/karafka/web/pro/commanding/commands/quiet.rb
lib/karafka/web/pro/commanding/commands/stop.rb
lib/karafka/web/pro/ui/views/consumers/_consumer_controls.erb
spec/lib/karafka/web/pro/commanding/commands/probe_spec.rb
spec/lib/karafka/web/pro/commanding/commands/quiet_spec.rb
spec/lib/karafka/web/pro/commanding/commands/stop_spec.rb
spec/lib/karafka/web/pro/ui/controllers/consumers_controller_spec.rb

close https://github.com/karafka/karafka-web/issues/370

Do not quiet or stop embedded via commanding

---

CHANGELOG.md
lib/karafka/web/pro/ui/controllers/dlq_controller.rb
spec/lib/karafka/web/pro/ui/controllers/dlq_controller_spec.rb

close https://github.com/karafka/karafka-web/issues/374

fix invalid dlq list classification

---

lib/karafka/web/pro/ui/controllers/search_controller.rb
lib/karafka/web/pro/ui/lib/search/matchers/base.rb
lib/karafka/web/pro/ui/lib/search/runner.rb
spec/lib/karafka/web/pro/ui/controllers/search_controller_spec.rb
spec/lib/karafka/web/pro/ui/lib/search/matchers/base_spec.rb
spec/lib/karafka/web/pro/ui/lib/search/matchers/raw_header_includes_spec.rb
spec/lib/karafka/web/pro/ui/lib/search/matchers/raw_key_includes_spec.rb
spec/lib/karafka/web/pro/ui/lib/search/matchers/raw_payload_includes_spec.rb

close https://github.com/karafka/karafka-web/issues/373

Topic specific search matchers

---

CHANGELOG.md
karafka-web.gemspec

ref https://github.com/karafka/karafka/issues/2177

fix invalid spdx license

---

.github/workflows/ci.yml

This PR adds assets building to the CI so we test that all works.

build assets in the pipeline

---

CHANGELOG.md
lib/karafka/web/pro/commanding/commands/base.rb
lib/karafka/web/pro/commanding/commands/quiet.rb
lib/karafka/web/pro/commanding/commands/stop.rb
lib/karafka/web/pro/ui/views/consumers/_consumer_controls.erb
lib/karafka/web/pro/ui/views/consumers/consumer/_commands.erb
lib/karafka/web/tracking/consumers/contracts/report.rb
lib/karafka/web/tracking/consumers/sampler.rb
spec/fixtures/consumers_reports/multi_partition/v1.4.0_process_1.json
spec/fixtures/consumers_reports/multi_partition/v1.4.0_process_2.json
spec/fixtures/consumers_reports/v1.4.0.json
spec/lib/karafka/web/pro/commanding/commands/quiet_spec.rb
spec/lib/karafka/web/pro/commanding/commands/stop_spec.rb
spec/lib/karafka/web/pro/ui/controllers/consumers_controller_spec.rb
spec/lib/karafka/web/tracking/consumers/contracts/report_spec.rb

close https://github.com/karafka/karafka-web/issues/390

Do not control swarm and embedded consumers

---

CHANGELOG.md
lib/karafka/web/tracking/consumers/contracts/job.rb
lib/karafka/web/tracking/consumers/listeners/processing.rb
spec/lib/karafka/web/tracking/consumers/listeners/processing_spec.rb
spec/lib/karafka/web/ui/controllers/jobs_controller_spec.rb

This PR adds support to `#eofed` job and action.

Support eofed

---

CHANGELOG.md
lib/karafka/web/tracking/consumers/listeners/errors.rb

close https://github.com/karafka/karafka-web/issues/421

Fix leaking error on details extraction for nil seek_offset case

---

CHANGELOG.md
lib/karafka/web/ui/base.rb
lib/karafka/web/ui/helpers/application_helper.rb

close https://github.com/karafka/karafka-web/issues/430
specs for this are already ready and will be added to the karafka integration suite once this is released.

deep merge without AS

---

.github/workflows/ci.yml

same as web ui - time to slowly say goodbye to 3.0 with the official date in few weeks.

drop 3.0 specs

---

CHANGELOG.md
lib/karafka/web.rb
lib/karafka/web/pro/loader.rb

This PR adds late pro loading detection (post web require) to support complex cases when karafka is loaded in weird ways

Support pro late loading

---

CHANGELOG.md
lib/karafka/web/management/actions/create_topics.rb

close https://github.com/karafka/karafka-web/issues/450

change retention for redpanda

---

.github/workflows/ci.yml

ref https://github.com/karafka/karafka/issues/2371

use ruby 3.4 as default

---

.github/workflows/ci.yml
bin/verify_kafka_warnings

ref https://github.com/karafka/karafka/issues/2358

verify post execution kafka warnings

---

lib/karafka/web/pro/ui/routes/explorer.rb
lib/karafka/web/pro/ui/routes/scheduled_messages.rb
lib/karafka/web/pro/ui/views/errors/partition.erb
lib/karafka/web/pro/ui/views/explorer/explorer/partition.erb
lib/karafka/web/pro/ui/views/scheduled_messages/explorer/partition.erb
spec/lib/karafka/web/pro/ui/controllers/explorer/explorer_controller_spec.rb
spec/lib/karafka/web/pro/ui/controllers/scheduled_messages/explorer_controller_spec.rb

Part 1 of https://github.com/karafka/karafka-web/issues/339
supports using urls to jump to offsets on partitions.

support url offset search

---

CHANGELOG.md
lib/karafka/web/ui/views/layout.erb
lib/karafka/web/ui/views/shared/_content.erb

close https://github.com/karafka/karafka-web/issues/521

fix breadcrumbs refresh

---

lib/karafka/web/pro/commanding/commands/base.rb
lib/karafka/web/pro/commanding/dispatcher.rb
lib/karafka/web/pro/commanding/manager.rb
spec/fixtures/consumers_commands/current.json
spec/fixtures/consumers_commands/v1.1.0_quiet.json
spec/fixtures/consumers_commands/v1.1.0_quiet_all.json
spec/fixtures/consumers_commands/v1.1.0_stop.json
spec/fixtures/consumers_commands/v1.1.0_stop_all.json
spec/fixtures/consumers_commands/v1.1.0_trace.json
spec/fixtures/consumers_commands/v1.1.0_trace_result.json
spec/lib/karafka/web/pro/commanding/commands/quiet_spec.rb
spec/lib/karafka/web/pro/commanding/commands/stop_spec.rb
spec/lib/karafka/web/pro/commanding/commands/trace_spec.rb
spec/lib/karafka/web/pro/commanding/manager_spec.rb
spec/lib/karafka/web/pro/ui/controllers/consumers/commanding_controller_spec.rb
spec/lib/karafka/web/pro/ui/controllers/consumers/commands_controller_spec.rb

part 1 of https://github.com/karafka/karafka-web/issues/471

provide ability to pass arguments to commands

---

CHANGELOG.md
config/locales/pro_errors.yml
lib/karafka/web/config.rb
lib/karafka/web/contracts/config.rb
lib/karafka/web/pro/ui/views/shared/_navigation.erb
lib/karafka/web/ui/routes/assets.rb
lib/karafka/web/ui/views/shared/_custom_nav.erb
lib/karafka/web/ui/views/shared/_header.erb
lib/karafka/web/ui/views/shared/_navigation.erb
spec/fixtures/custom/nav.erb
spec/lib/karafka/web/contracts/config_spec.rb
spec/lib/karafka/web/pro/ui/controllers/base_controller_spec.rb
spec/lib/karafka/web/ui/controllers/base_controller_spec.rb
spec/support/fixtures.rb

close https://github.com/karafka/karafka-web/issues/575

Allow for extra nav at the bottom via custom erb template

---

spec/support/links_validator.rb

close https://github.com/karafka/karafka-web/issues/594

exclude status controller from post-link verif

---

CHANGELOG.md
lib/karafka/web/ui/base.rb
spec/lib/karafka/web/pro/ui/controllers/explorer/explorer_controller_spec.rb

close https://github.com/karafka/karafka-web/issues/620

fix incorrect redirect match

---

CHANGELOG.md
config/locales/slogans.yml
lib/karafka/web/pro/ui/controllers/errors_controller.rb
lib/karafka/web/pro/ui/controllers/explorer/explorer_controller.rb
lib/karafka/web/pro/ui/views/errors/_breadcrumbs.erb
lib/karafka/web/pro/ui/views/errors/show.erb
lib/karafka/web/pro/ui/views/explorer/explorer/show.erb
lib/karafka/web/ui/controllers/errors_controller.rb
lib/karafka/web/ui/models/message.rb
lib/karafka/web/ui/routes/errors.rb
lib/karafka/web/ui/views/errors/_breadcrumbs.erb
lib/karafka/web/ui/views/errors/show.erb
lib/karafka/web/ui/views/shared/_compacted_message_info.erb
spec/lib/karafka/web/pro/ui/controllers/errors_controller_spec.rb
spec/lib/karafka/web/pro/ui/controllers/explorer/explorer_controller_spec.rb
spec/lib/karafka/web/ui/controllers/errors_controller_spec.rb

close https://github.com/karafka/karafka-web/issues/691
close https://github.com/karafka/karafka-web/issues/517

support transactional exploration without errors
