karafka/karafka-web

CHANGELOG.md, Gemfile, Gemfile.lock, karafka-web.gemspec, lib/karafka/web/tracking/consumers/listeners/errors.rb, spec/lib/karafka/web/tracking/consumers/listeners/errors_spec.rb, spec/spec_helper.rb
it turns out ppl raise error with frozen messages and we try to force encoding change on them and it fails. We can just dup and go on since it's an error path.
Example:
```ruby
StandardError.new(-'a').message.to_s.force_encoding('utf-8')
```
=> Fix encoding force on a frozen error message

CHANGELOG.md, lib/karafka/web/tracking/consumers/listeners/errors.rb, lib/karafka/web/tracking/consumers/sampler.rb, lib/karafka/web/tracking/reporter.rb
This PR slightly reorganizes error collecting.
- Put process_name in process namespace similar to how it is done with metrics reporting
- Add process tags for errors - to get better visibility
- Build whole error object inside the error listener and not delegate process data injection to the reporter.
This change is backwards compatible so no problems with the UI.
=> Collect process tags for errors

CHANGELOG.md, Gemfile.lock, karafka-web.gemspec, lib/karafka/web/installer.rb
This PR ensures that the web topics are not managed declaratively (for now) and adds missing time limit on errors storage.
=> Do not manage declaratively web topics

CHANGELOG.md, lib/karafka/web/tracking/consumers/listeners/statistics.rb, lib/karafka/web/ui/helpers/application_helper.rb, lib/karafka/web/ui/pro/views/consumers/consumer/_partition.erb, lib/karafka/web/ui/pro/views/explorer/_detail.erb, lib/karafka/web/ui/pro/views/explorer/_message.erb
This PR tackles few things:
- [Improvement] Replace the "x time ago" in the code explorer with an exact date (`2023-04-12 10:16:48.596 +0200 `).
- [Improvement] When hovering over a message timestamp, a label with raw numeric timestamp will be presented.
- [Improvement] Do not skip reporting on partitions subscribed that never received any messages.
- [Fix] Skip reporting data on subscriptions that were revoked and not only stopped by us.
close https://github.com/karafka/karafka-web/issues/50
=> Reporting remarks

CHANGELOG.md, Gemfile.lock, lib/karafka/web/tracking/consumers/contracts/report.rb, lib/karafka/web/tracking/consumers/sampler.rb, lib/karafka/web/tracking/sampler.rb, lib/karafka/web/ui/models/status.rb, lib/karafka/web/ui/pro/views/consumers/consumer/_metrics.erb, lib/karafka/web/ui/views/status/failures/_initial_state.erb, lib/karafka/web/ui/views/status/info/_components.erb, lib/karafka/web/ui/views/status/show.erb, lib/karafka/web/ui/views/status/successes/_connection.erb, lib/karafka/web/ui/views/status/warnings/_connection.erb, lib/karafka/web/version.rb, spec/lib/karafka/web/tracking/consumers/contracts/consumer_group_spec.rb, spec/lib/karafka/web/tracking/consumers/contracts/job_spec.rb, spec/lib/karafka/web/tracking/consumers/contracts/report_spec.rb, spec/lib/karafka/web/tracking/consumers/contracts/subscription_group_spec.rb, spec/lib/karafka/web/tracking/consumers/contracts/topic_spec.rb, spec/lib/karafka/web/tracking/sampler_spec.rb
close https://github.com/karafka/karafka-web/issues/69
close https://github.com/karafka/karafka-web/issues/68
close https://github.com/karafka/karafka/issues/1454
=> Content improvements

CHANGELOG.md, Gemfile.lock, lib/karafka/web/tracking/consumers/reporter.rb, lib/karafka/web/version.rb
This affects ANY clock type but on HPET it is visible the most.
=> Fix extensive thread interrupts on HPET clocks

CHANGELOG.md, lib/karafka/web.rb, lib/karafka/web/config.rb, lib/karafka/web/contracts/config.rb, lib/karafka/web/management/clean_boot_file.rb, lib/karafka/web/management/extend_boot_file.rb, lib/karafka/web/ui/base.rb, spec/lib/karafka/web/contracts/config_spec.rb, spec/lib/karafka/web/management/extend_boot_file_spec.rb
This PR introduces config validation + sessions management plugin usage and CSRF plugin from Roda.
They are NOT used at the moment but are needed for some operations in the future, hence introduction with 0.7.0 as it's anyhow breaking and requires manual upgrade path.
close https://github.com/karafka/karafka-web/issues/77
=> Config validation + session management

CHANGELOG.md, lib/karafka/web.rb, lib/karafka/web/app.rb, lib/karafka/web/ui/base.rb, lib/karafka/web/ui/controllers/base.rb, lib/karafka/web/ui/controllers/responses/redirect.rb, lib/karafka/web/ui/helpers/paths_helper.rb, lib/karafka/web/ui/pro/app.rb, lib/karafka/web/ui/pro/controllers/explorer.rb, lib/karafka/web/ui/pro/controllers/messages.rb, lib/karafka/web/ui/pro/views/explorer/show.erb, lib/karafka/web/ui/public/javascripts/application.js, lib/karafka/web/ui/views/layout.erb, lib/karafka/web/ui/views/shared/_flashes.erb, spec/lib/karafka/web/ui/pro/controllers/explorer_spec.rb, spec/lib/karafka/web/ui/pro/controllers/messages_spec.rb, spec/spec_helper.rb
This PR introduces a "Reproduce" button to dispatch same message again with all the data and metadata to the same topic partition and introduces a "surrounding" button that redirects you to the offset page that presents messages before and after the viewed message for ease of debugging
=> Messages reproduce and surrounding link

CHANGELOG.md, lib/karafka/web/cli.rb
There were several cases where people would not set up prod with decent replication. This PR changes that by using cluster awareness to decide if use no replication or replication of two
=> Use cluster data for default replication

CHANGELOG.md, Gemfile.lock, karafka-web.gemspec, lib/karafka/web/tracking/consumers/contracts/partition.rb, lib/karafka/web/tracking/consumers/listeners/statistics.rb, spec/lib/karafka/web/tracking/consumers/contracts/consumer_group_spec.rb, spec/lib/karafka/web/tracking/consumers/contracts/partition_spec.rb, spec/lib/karafka/web/tracking/consumers/contracts/report_spec.rb, spec/lib/karafka/web/tracking/consumers/contracts/subscription_group_spec.rb, spec/lib/karafka/web/tracking/consumers/contracts/topic_spec.rb, spec/lib/karafka/web/tracking/sampler_spec.rb
This PR extends what we report from consumers to report LSO (last stable offset) per consumer group plus few other metrics.
We want to report LSO per consumer group because of the different isolation levels on which they can operate.
Extra missing specs were added as well.
=> Report LSO and other offsets

CHANGELOG.md, Gemfile.lock, lib/karafka/web/ui/views/dashboard/index.erb, lib/karafka/web/version.rb
I removed it for testing and forgot to restore:
close https://github.com/karafka/karafka-web/issues/126
=> Restore errors for OSS in dashboard charts

CHANGELOG.md, lib/karafka/web/ui/models/processes.rb, spec/lib/karafka/web/ui/controllers/consumers_spec.rb, spec/lib/karafka/web/ui/controllers/jobs_spec.rb, spec/lib/karafka/web/ui/pro/controllers/consumers_spec.rb, spec/lib/karafka/web/ui/pro/controllers/jobs_spec.rb
This PR changes how we fetch process details. Because since web 0.5.0 we publish process name as the key alongside payload, we can use it to uniquely squash data. This prevents us from extensive parsing of JSONs. We can also early skip when no processes saving us request to Kafka
close https://github.com/karafka/karafka-web/issues/131
=> Fix extensive data polling and deserialization on expired processes states

.github/workflows/ci.yml, bin/wait_for_kafka, docker-compose.yml
This PR replaces the docker setup with confluent kafka + adds bundler cache as we don't care here about recompiling and we do not do intermediate bundling.
We're removing one spec because bundler-cache caches zstd so we don't have how to check it. We check it in Karafka nonetheless the same way.
=> Replace Docker and use Bundler cache

lib/karafka/web/errors.rb, lib/karafka/web/installer.rb, lib/karafka/web/processing/consumers/metrics.rb, lib/karafka/web/processing/consumers/state.rb, spec/lib/karafka/web/processing/consumers/metrics_spec.rb, spec/lib/karafka/web/processing/consumers/state_spec.rb
This PR replaces the general messages about missing topics with dedicated once to ease with the zero-downtime migrations awareness.
=> better processing crash errors

CHANGELOG.md, Gemfile.lock, karafka-web.gemspec, lib/karafka/web.rb, lib/karafka/web/config.rb, lib/karafka/web/management/create_initial_states.rb, lib/karafka/web/management/enable.rb, lib/karafka/web/processing/consumer.rb, lib/karafka/web/tracking/consumers/reporter.rb, lib/karafka/web/tracking/producers/reporter.rb, lib/karafka/web/tracking/reporter.rb, lib/karafka/web/ui/pro/controllers/messages.rb, spec/lib/karafka/web/tracking/producers/reporter_spec.rb, spec/lib/karafka/web/tracking/reporter_spec.rb
close https://github.com/karafka/karafka-web/issues/194
This allows for better resources utilization and improved reporting when using web-ui with transactional consumers as the web reporting dedicated consumer can be configured independently.
=> Provide ability to use karafka-web dedicated producer

CHANGELOG.md, Gemfile.lock, lib/karafka/web/processing/consumers/aggregators/metrics.rb, lib/karafka/web/ui/models/metrics/charts/topics.rb, lib/karafka/web/version.rb, spec/lib/karafka/web/processing/consumers/aggregators/metrics_spec.rb
Per partition Health was reporting correctly, the issue was just with the graph aggregation.
close https://github.com/karafka/karafka-web/issues/201
=> Fix invalid reporting and display of the LSO graph

CHANGELOG.md, lib/karafka/web/ui/views/errors/show.erb, spec/lib/karafka/web/ui/controllers/errors_spec.rb
This PR exposes errors backtraces in OSS. I gave it a second thought and I think this is one of the things users should not pay for as it is a critical thing when debugging regular issues. Similar to Sidekiq.
close https://github.com/karafka/karafka-web/issues/213
=> Promote backtrace to OSS

CHANGELOG.md, lib/karafka/web/ui/app.rb, lib/karafka/web/ui/controllers/jobs.rb, lib/karafka/web/ui/models/jobs.rb, lib/karafka/web/ui/pro/app.rb, lib/karafka/web/ui/pro/controllers/consumers.rb, lib/karafka/web/ui/pro/views/consumers/_counters.erb, lib/karafka/web/ui/pro/views/consumers/consumer/_no_jobs.erb, lib/karafka/web/ui/pro/views/consumers/consumer/_tabs.erb, lib/karafka/web/ui/pro/views/consumers/pending_jobs.erb, lib/karafka/web/ui/pro/views/jobs/_no_jobs.erb, lib/karafka/web/ui/pro/views/jobs/pending.erb, lib/karafka/web/ui/pro/views/jobs/running.erb, lib/karafka/web/ui/views/consumers/_counters.erb, lib/karafka/web/ui/views/jobs/_breadcrumbs.erb, lib/karafka/web/ui/views/jobs/_no_jobs.erb, lib/karafka/web/ui/views/jobs/_tabs.erb, lib/karafka/web/ui/views/jobs/pending.erb, spec/lib/karafka/web/ui/controllers/jobs_spec.rb, spec/lib/karafka/web/ui/models/jobs_spec.rb, spec/lib/karafka/web/ui/pro/controllers/consumers_spec.rb, spec/lib/karafka/web/ui/pro/controllers/jobs_spec.rb
This PR introduces:
Global pending jobs visibility:
Per process pending jobs visibility:
close https://github.com/karafka/karafka-web/issues/207
=> Pending jobs visibility

CHANGELOG.md, lib/karafka/web/tracking/consumers/contracts/job.rb, lib/karafka/web/tracking/consumers/listeners/processing.rb, spec/lib/karafka/web/ui/pro/controllers/jobs_spec.rb
This PR adds support for https://karafka.io/docs/Pro-Periodic-Jobs/ in the web UI. It displays the `#tick` methods invocations and includes them in the utilization cost computation.
close https://github.com/karafka/karafka-web/issues/228
=> Support for Periodics

CHANGELOG.md, lib/karafka/web/config.rb, lib/karafka/web/contracts/config.rb, lib/karafka/web/installer.rb, lib/karafka/web/management/actions/enable.rb, lib/karafka/web/management/actions/extend_boot_file.rb, spec/lib/karafka/web/contracts/config_spec.rb
This PR:
- makes sure we cannot double-enable web-ui - while here it is a side effect it was part of a different user struggle
- injects routing and deserialization logic PRIOR to migrations, making sure proper deserializer is selected
- installs web-ui even if enabled code is present as long as it is commented out
close https://github.com/karafka/karafka-web/issues/259
close https://github.com/karafka/karafka-web/issues/260
=> Make sure routing setup is prior to running migration on fresh install

lib/karafka/web/installer.rb
I figured out we might as well always enable web UI before an actions as it does not rely on kafka state and just makes things consistent.
=> always enable web for actions

CHANGELOG.md, lib/karafka/web/tracking/consumers/contracts/subscription_group.rb, lib/karafka/web/ui/pro/views/consumers/consumer/_subscription_group.erb, spec/lib/karafka/web/tracking/consumers/contracts/subscription_group_spec.rb, spec/lib/karafka/web/ui/pro/controllers/consumers_spec.rb
close https://github.com/karafka/karafka-web/issues/265
=> Support empty rebalance reason

lib/karafka/web/management/migrations/0_base.rb
In some (perhaps misguided) cases, classes elsewhere (i.e. in a Rails app, or in another gem that's also been loaded) may override the <=> method (on the class, not the instance). This causes the inheritance check via the less-than operator to throw an exception.
So instead, let’s use the `ancestors` method, which is less likely to be altered by other code. A class’s ancestors always includes itself, so we need to ignore the base class as well.
=> Check migration inheritance via ancestors array

CHANGELOG.md, lib/karafka/web/ui/views/shared/exceptions/not_found.erb
we have changed the command to `migrate` while ago to differentiate. This PR aligns the 404 (other places are aligned)
=> fix 404 recom

lib/karafka/web/pro/commanding/dispatcher.rb, lib/karafka/web/pro/ui/app.rb, lib/karafka/web/pro/ui/views/topics/_breadcrumbs.erb, lib/karafka/web/pro/ui/views/topics/_tabs.erb, lib/karafka/web/pro/ui/views/topics/_topic.erb, spec/lib/karafka/web/pro/ui/controllers/topics_controller_spec.rb
Small remarks that came when a user upgraded to RC:
1. topics details routes are not restful
2. all other karafka web UI related data is compressed in ruby and decompressed to preserver space but not commands
this PR addresses both
=> compress commands and make topic explorer better

lib/karafka/web/pro/ui/app.rb, lib/karafka/web/ui/views/layout.erb
this PR fixes error pages classes and ensures that assets are loaded even when policies prevent anything because those are public assets.
=> ensure error pages work

CHANGELOG.md, lib/karafka/web/pro/commanding.rb, lib/karafka/web/pro/commanding/commands/trace.rb, lib/karafka/web/pro/commanding/listener.rb, lib/karafka/web/pro/commanding/manager.rb, lib/karafka/web/pro/ui/app.rb, lib/karafka/web/pro/ui/controllers/commanding_controller.rb, lib/karafka/web/pro/ui/views/commands/_command.erb, lib/karafka/web/pro/ui/views/consumers/_consumer_controls.erb, lib/karafka/web/pro/ui/views/consumers/consumer/_commands.erb, spec/fixtures/consumers_commands/v1.0.0_trace.json, spec/fixtures/consumers_commands/v1.0.0_trace_result.json, spec/lib/karafka/web/pro/commanding/commands/trace_spec.rb, spec/lib/karafka/web/pro/commanding/manager_spec.rb, spec/lib/karafka/web/pro/ui/controllers/commanding_controller_spec.rb, spec/lib/karafka/web/pro/ui/controllers/commands_controller_spec.rb, spec/lib/karafka/web/pro/ui/controllers/consumers_controller_spec.rb
just a simple rename as we technically trace those processes
=> rename probing to tracing

CHANGELOG.md, lib/karafka/web/pro/ui/controllers/routing_controller.rb, lib/karafka/web/pro/ui/views/routing/_consumer_group.erb, lib/karafka/web/pro/ui/views/routing/_topic.erb, spec/lib/karafka/web/pro/ui/controllers/routing_controller_spec.rb
since "active" is a state on a web UI process, it may not reflect the assignment value. This PR fixes that by displaying both.
While assignment is tricky as it is per partition, this gives a general overview and answers the "is anyone consuming this atm at all" question. This was a frequently requested improvement.
close https://github.com/karafka/karafka-web/issues/367
=> Display assignment status per topic in pro routing

CHANGELOG.md, lib/karafka/web/config.rb, lib/karafka/web/contracts/config.rb, lib/karafka/web/tracking/producers/reporter.rb, spec/lib/karafka/web/contracts/config_spec.rb
This PR moves the `sync_threshold` for producers similar to how it already is for consumers.
=> move sync threshold for producers

CHANGELOG.md, lib/karafka/web.rb, lib/karafka/web/errors.rb, spec/lib/karafka/web/errors_spec.rb
close https://github.com/karafka/karafka-web/issues/484
I will add integration spec in karafka because a clean slate is required (not supported in web specs atm)
=> Error out when setup is called after web is enabled

lib/karafka/web/tracking/consumers/sampler.rb, lib/karafka/web/tracking/helpers/sysconf.rb
Currently, karafka-web doesn't work properly across various container-based OSes (e.g. debian-based images have taken away the `ps` command, ruby distroless-like containers do not necessarily have all the CLI tools available that are invoked in the sampler.rb code such as `ps` and `w`, alpine's `ps` is not equivalent to the `procps` output that is expected by karafka-web).
This PR contains changes to the Tracking::Consumers::Sampler class such that the methods for gathering `memory_size` , `cpu_usage` (or load averages), and memory stats (rss, thcount, pid) are compatible with debian/alpine/wolfi container image OSes.
=> Make consumer sampler/stats gathering compatible across debian/alpine/wolfi OSes

.github/workflows/ci.yml, CHANGELOG.md, bin/verify_topics_naming
ref https://github.com/karafka/karafka/issues/2454
=> verify kafka topics naming convention

CHANGELOG.md, lib/karafka/web/ui/views/dashboard/_feature_pro.erb, lib/karafka/web/ui/views/dashboard/index.erb
This PR promotes RSS and lags charts to OSS.
With the recent advancements in the Pro Web UI, several new features, as part of my "leaking to OSS" benefit I decided to OSS those. They should help users notice memory leaks and lags fast even if those users cannot use Pro.
=> Promote charts to oss

spec/support/links_validator.rb
Improves specs stability by excluding some of the extra link verifications from the routing controller that checks invalid states.
ref https://github.com/karafka/karafka-web/actions/runs/14323063344/job/40143528414
=> stabilize specs

bin/verify_kafka_warnings
similar to the karafka repo, those warnings are valid in our specs.
=> expand allowed kafka warnings

CHANGELOG.md, lib/karafka/web/ui/controllers/base_controller.rb
This PR removes the upgrade notes from changelog and moves them to wiki similar to karafka to have cohesive setup.
=> fix typo and move upgrade notes to wiki
